/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from './interfaces/index.js';
export { UniswapV2ERC20__factory } from './UniswapV2ERC20__factory.js';
export { UniswapV2Factory__factory } from './UniswapV2Factory__factory.js';
export { UniswapV2Pair__factory } from './UniswapV2Pair__factory.js';