/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from './IERC20.js';
export type { IUniswapV2Router01 } from './IUniswapV2Router01.js';
export type { IUniswapV2Router02 } from './IUniswapV2Router02.js';
export type { IWETH } from './IWETH.js';