// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface Math$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "Math";
  readonly sourceName: "contracts/uniswap-v2-core/libraries/Math.sol";
  readonly abi: [];
  readonly bytecode: "0x60556023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea265627a7a72315820c7466cddc626eb0d9fcb5f97e0242112b3556cc60b011a01b2c855a0814a785464736f6c63430005100032";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea265627a7a72315820c7466cddc626eb0d9fcb5f97e0242112b3556cc60b011a01b2c855a0814a785464736f6c63430005100032";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/uniswap-v2-core/libraries/Math.sol";
  readonly buildInfoId: "solc-0_5_16-533381cafabb5055bedd4d038d9ef0f2617e74bf";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["Math"]: Math$Type;
    ["contracts/uniswap-v2-core/libraries/Math.sol:Math"]: Math$Type;
  }
}