// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface UQ112x112$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "UQ112x112";
  readonly sourceName: "contracts/uniswap-v2-core/libraries/UQ112x112.sol";
  readonly abi: [];
  readonly bytecode: "0x60556023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea265627a7a723158209c983376c783267b6b99c713f7cdffa80e725c4a267626584b105f6c813765c564736f6c63430005100032";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea265627a7a723158209c983376c783267b6b99c713f7cdffa80e725c4a267626584b105f6c813765c564736f6c63430005100032";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/uniswap-v2-core/libraries/UQ112x112.sol";
  readonly buildInfoId: "solc-0_5_16-533381cafabb5055bedd4d038d9ef0f2617e74bf";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["UQ112x112"]: UQ112x112$Type;
    ["contracts/uniswap-v2-core/libraries/UQ112x112.sol:UQ112x112"]: UQ112x112$Type;
  }
}