// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface UniswapV2Library$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "UniswapV2Library";
  readonly sourceName: "contracts/uniswap-v2-periphery/libraries/UniswapV2Library.sol";
  readonly abi: [];
  readonly bytecode: "0x60566023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220950f23572c47da702eaebac40c5543fc24093ad5873c548a5d23f839dd7cc53064736f6c63430006060033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220950f23572c47da702eaebac40c5543fc24093ad5873c548a5d23f839dd7cc53064736f6c63430006060033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/uniswap-v2-periphery/libraries/UniswapV2Library.sol";
  readonly buildInfoId: "solc-0_6_6-7424790a315c2388a7366956d7ae20cf02edac3c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["UniswapV2Library"]: UniswapV2Library$Type;
    ["contracts/uniswap-v2-periphery/libraries/UniswapV2Library.sol:UniswapV2Library"]: UniswapV2Library$Type;
  }
}