// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SafeMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SafeMath";
  readonly sourceName: "contracts/uniswap-v2-periphery/libraries/SafeMath.sol";
  readonly abi: [];
  readonly bytecode: "0x60566023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122034bc38cf43ca0afb37f740f32cdbe752700081b7a7effc3c024747c30be43e4e64736f6c63430006060033";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea264697066735822122034bc38cf43ca0afb37f740f32cdbe752700081b7a7effc3c024747c30be43e4e64736f6c63430006060033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/uniswap-v2-periphery/libraries/SafeMath.sol";
  readonly buildInfoId: "solc-0_6_6-7424790a315c2388a7366956d7ae20cf02edac3c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SafeMath"]: SafeMath$Type;
    ["contracts/uniswap-v2-periphery/libraries/SafeMath.sol:SafeMath"]: SafeMath$Type;
  }
}