// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface SafeMath$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "SafeMath";
  readonly sourceName: "contracts/uniswap-v2-core/libraries/SafeMath.sol";
  readonly abi: [];
  readonly bytecode: "0x60556023600b82828239805160001a607314601657fe5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea265627a7a72315820eb4311c40707b3d34d9a2c74a1242ea9922a2978dce0f785490001ad793926d164736f6c63430005100032";
  readonly deployedBytecode: "0x73000000000000000000000000000000000000000030146080604052600080fdfea265627a7a72315820eb4311c40707b3d34d9a2c74a1242ea9922a2978dce0f785490001ad793926d164736f6c63430005100032";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/uniswap-v2-core/libraries/SafeMath.sol";
  readonly buildInfoId: "solc-0_5_16-533381cafabb5055bedd4d038d9ef0f2617e74bf";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["SafeMath"]: SafeMath$Type;
    ["contracts/uniswap-v2-core/libraries/SafeMath.sol:SafeMath"]: SafeMath$Type;
  }
}