/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from './interfaces/index.js';
export type { interfaces };
export type { UniswapV2ERC20 } from './UniswapV2ERC20.js';
export type { UniswapV2Factory } from './UniswapV2Factory.js';
export type { UniswapV2Pair } from './UniswapV2Pair.js';