/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from './IERC20.js';
export type { IUniswapV2Callee } from './IUniswapV2Callee.js';
export type { IUniswapV2ERC20 } from './IUniswapV2ERC20.js';
export type { IUniswapV2Factory } from './IUniswapV2Factory.js';
export type { IUniswapV2Pair } from './IUniswapV2Pair.js';