// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface TransferHelper$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "TransferHelper";
  readonly sourceName: "contracts/uniswap-v2-periphery/libraries/TransferHelper.sol";
  readonly abi: [];
  readonly bytecode: "0x6055604b600b8282823980515f1a607314603f577f4e487b71000000000000000000000000000000000000000000000000000000005f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220c28694b99e5f11c00df3c2aa039561b3714476de85bf747cdb25a834bef549ee64736f6c634300081c0033";
  readonly deployedBytecode: "0x730000000000000000000000000000000000000000301460806040525f5ffdfea2646970667358221220c28694b99e5f11c00df3c2aa039561b3714476de85bf747cdb25a834bef549ee64736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/uniswap-v2-periphery/libraries/TransferHelper.sol";
  readonly buildInfoId: "solc-0_8_28-66cc4c60f959316a3264672cf9fea1acaa7cc667";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["TransferHelper"]: TransferHelper$Type;
    ["contracts/uniswap-v2-periphery/libraries/TransferHelper.sol:TransferHelper"]: TransferHelper$Type;
  }
}