// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IUniswapV2Router02"]: never
    ["IERC20"]: never
    ["IUniswapV2Factory"]: never
    ["IUniswapV2Pair"]: never
    ["SafeMath"]: never;
  }
}